Template for service ui cards
WSU-4110/WayneSociety pull request #47
Opened 2021-07-01 14:25 UTC by herskovitz2000

Made 3 templates for cards that will contain actual services

2021-07-02 13:05 UTC, erahman99 reviewed
Nice use of comments your code is well organized and easy to read

2021-07-02 14:01 UTC, CalebObsCode requested changes

2021-07-02 14:01 UTC, CalebObsCode commented on WayneSociety_Project/templates/Services.html
>      <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700
We might need to get rid of this

2021-07-02 14:01 UTC, CalebObsCode commented on WayneSociety_Project/templates/Services.html
> +<<<<<<< HEAD
Please resolve merge conflict, so this doesn't break production

2021-07-05 23:46 UTC, CalebObsCode approved these changes

2021-07-05 23:48 UTC, merged